CREATE DATABASE IF NOT EXISTS CineVault CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE CineVault;

CREATE TABLE IF NOT EXISTS Movie (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL UNIQUE,
  duration INT,
  year INT,
  poster TEXT,
  description TEXT
);

CREATE TABLE IF NOT EXISTS Genre (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Actor (
  id INT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(100),
  last_name VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS Director (
  id INT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(100),
  last_name VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS Language (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE
);